#!/bin/sh -ex

# Called by "git commit" with no arguments. The hook should exit with non-zero status after issuing
# an appropriate message if it wants to stop the commit.

# Run the linter.
rubocop -a
