inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  Exclude:
    - test/db/*schema.rb
    - vendor
  SuggestExtensions: false

Layout/LineLength:
  Enabled: true
  Max: 100
  AllowedPatterns:
    # Allow long comments.
    - "^#.*"

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
