service: rails-rest-framework

image: ghcr.io/gregschmit/rails-rest-framework
labels:
  org.opencontainers.image.source: https://github.com/gregschmit/rails-rest-framework
builder:
  multiarch: false

servers:
  web:
    - app0.schmit.net
    - app1.schmit.net
  worker:
    hosts:
      - app0.schmit.net
    cmd: bin/rails solid_queue:start

traefik:
  host_port: 8081

ssh:
  proxy: deploy@home.schmit.net

registry:
  server: ghcr.io
  username: gregschmit
  password:
    - GITHUB_TOKEN

env:
  secret:
    - PRODUCTION_KEY
