service: rails-rest-framework
image: ghcr.io/gregschmit/rails-rest-framework
builder:
  arch: amd64

servers:
  web:
    - app0.schmit.net
  worker:
    cmd: bin/jobs
    hosts:
      - app1.schmit.net

proxy:
  host: rails-rest-framework.com
  app_port: 3000

ssh:
  proxy: deploy@home.schmit.net

registry:
  server: ghcr.io
  username: gregschmit
  password:
    - GITHUB_TOKEN

env:
  secret:
    - GITHUB_TOKEN
    - PRODUCTION_KEY
