service: rails-rest-framework

image: ghcr.io/gregschmit/rails-rest-framework
labels:
  org.opencontainers.image.source: https://github.com/gregschmit/rails-rest-framework
builder:
  multiarch: false

servers:
  web:
    hosts:
      - app0.schmit.net
      - app1.schmit.net
    labels:
      traefik.http.routers.rrf.rule: Host(`rails-rest-framework.com`) || HostRegexp(`^.+\.rails-rest-framework\.com$`) || Query(`_route_to`, `rrf`)
  worker:
    cmd: bin/rails solid_queue:start
    hosts:
      - app0.schmit.net

ssh:
  proxy: deploy@home.schmit.net

registry:
  server: ghcr.io
  username: gregschmit
  password:
    - GITHUB_TOKEN

env:
  secret:
    - PRODUCTION_KEY
