name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6.8", "2.7.5", "3.0.4"]
        RAILS_VERSION: ["6.0.6", "6.1.4", "7.0.4"]
        exclude:
        - ruby: 2.6.8
          RAILS_VERSION: 7.0.4
    steps:
    - name: Checkout code.
      uses: actions/checkout@v3
    - name: Remove Gemfile.lock for matrix jobs.
      run: rm Gemfile.lock
    - name: Install Ruby and gems.
      uses: ruby/setup-ruby@v1
      with: {bundler-cache: true}
    - name: Execute migrations.
      run: bin/rails db:migrate
    - name: Run tests
      run: BACKTRACE=1 bin/rails test
